app_user_set_password:
    pattern:  /set-password
    defaults: { _controller: AppUserBundle:SetPassword:edit }

app_user_set_password_update:
    pattern:  /set-password/update
    defaults: { _controller: AppUserBundle:SetPassword:update }
