parameters:
#    app_upload.example.class: App\UploadBundle\Example

services:
#    app_upload.example:
#        class: %app_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
